#!/bin/bash
# Script de ayuda para Chess Scouter

echo "♟️  Chess Scouter - Comandos Útiles"
echo "=================================="
echo ""
echo "📦 DESARROLLO LOCAL:"
echo "  npm run dev          → Iniciar frontend (localhost:5173)"
echo "  npm run server       → Iniciar backend IA (localhost:3001)"
echo "  npm run build        → Build para producción"
echo ""
echo "🚀 DESPLIEGUE (Cloudflare Pages):"
echo "  git push             → ¡Eso es todo! Cloudflare despliega automáticamente"
echo ""
echo "📝 CONFIGURACIÓN INICIAL:"
echo "  1. git init && git add . && git commit -m 'Initial commit'"
echo "  2. git remote add origin https://github.com/TU-USUARIO/chess-scouter.git"
echo "  3. git push -u origin main"
echo "  4. Conecta con Cloudflare Pages (ver QUICKSTART.md)"
echo ""
echo "📚 DOCUMENTACIÓN:"
echo "  README.md            → Documentación principal"
echo "  QUICKSTART.md        → Guía de despliegue (2 pasos)"
echo ""
echo "💡 TIP: El backend se despliega automáticamente con Pages Functions."
echo "    No necesitas Worker separado ni comandos extras de deploy."
echo ""
